workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build debug for simulator
        script: |
          # Este comando genera el archivo .app para simuladores
          flutter build ios --debug --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app